export const USER_PLAYER = 'USER_PLAYER';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';
export const NEXT_QUESTIONS = 'NEXT_QUESTIONS';
export const CHANGE_CLASS = 'CHANGE_CLASS';
export const RESET_PLAYER = 'RESET_PLAYER';
export const RESET_GAME = 'RESET_GAME';
