export const USER_PLAYER = 'USER_PLAYER';
export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';
export const GET_PLAYER_USER_INFO = 'GET_PLAYER_USER_INFO';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
