const settings = {
  categories: [
    { name: 'Any category', value: '' },
    { name: 'General Knowledge', value: 9 },
    { name: 'Entertainment: Books', value: 10 },
    { name: 'Entertainment: Film', value: 11 },
    { name: 'Entertainment: Music', value: 12 },
    { name: 'Entertainment: Musicals & Theatres', value: 13 },
    { name: 'Entertainment: Television', value: 14 },
    { name: 'Entertainment:  valueeo Games', value: 15 },
    { name: 'Entertainment: Board Game', value: 16 },
    { name: 'Entertainment: Science & Nature', value: 17 },
    { name: 'Science: Computers', value: 18 },
    { name: 'Science: Mathematics', value: 19 },
    { name: 'Mythology', value: 20 },
    { name: 'Sports', value: 21 },
    { name: 'Geography', value: 22 },
    { name: 'History', value: 23 },
    { name: 'Politics', value: 24 },
    { name: 'Art', value: 25 },
    { name: 'Celebrities', value: 26 },
    { name: 'Animals', value: 27 },
    { name: 'Vehicles', value: 28 },
    { name: 'Entertainment: Comics', value: 29 },
    { name: 'Science: Gadget', value: 30 },
    { name: 'Entertainment: Japanese Anime & Manga', value: 31 },
    { name: 'Entertainment: Cartoon & Animations', value: 32 },
  ],
  difficulty: [
    { name: 'Any difficulty', value: '' },
    { name: 'Easy', value: 'easy' },
    { name: 'Medium', value: 'medium' },
    { name: 'Hard', value: 'hard' },
  ],
  type: [
    { name: 'Any type', value: '' },
    { name: 'True / False', value: 'boolean' },
    { name: 'Multiple Choice', value: 'multiple' },
  ],
};

export default settings;
